name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-microservice:latest .

      - name: Verify image
        run: docker images

      - name: Save image
        run: docker save my-microservice:latest -o my-microservice.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-microservice-image
          path: my-microservice.tar